### ISSUE TITLE
Failed to resize snapshot

### ISSUE THREAD

**Issue by Blogoslov** [tropicoo/hikvision-camera-bot#102]
Hello, could you please help me to understand the root of the issue which I see in the log when I attempt to receive a snapshot from the stream using bot (not full pic - it works well)
I see the following error message in the log file:

`2023-06-17 11:19:35,973 - [ERROR] - [HikvisionCam:171] - [cam_1] Failed to resize snapshot taken from Alabushevo
Traceback (most recent call last):
  File "/app/hikcamerabot/camera.py", line 160, in take_snapshot
    await asyncio.get_running_loop().run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hikcamerabot/camera.py", line 161, in <lambda>
    None, lambda: self._img_processor.resize(image_obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hikcamerabot/utils/image.py", line 25, in resize
    snapshot: Image.Image = raw_snapshot.resize(Img.SIZE, Image.ANTIALIAS)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 2157, in resize
    self.load()
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 266, in load
    raise OSError(msg)
OSError: image file is truncated (21 bytes not processed)
2023-06-17 11:19:35,973 - [ERROR] - [AlarmNotifier:53] - Task "AlarmPicNotificationTask" raised an exception
Traceback (most recent call last):
  File "/app/hikcamerabot/camera.py", line 160, in take_snapshot
    await asyncio.get_running_loop().run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hikcamerabot/camera.py", line 161, in <lambda>
    None, lambda: self._img_processor.resize(image_obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hikcamerabot/utils/image.py", line 25, in resize
    snapshot: Image.Image = raw_snapshot.resize(Img.SIZE, Image.ANTIALIAS)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 2157, in resize
    self.load()
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 266, in load
    raise OSError(msg)
OSError: image file is truncated (21 bytes not processed)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/hikcamerabot/utils/task.py", line 49, in _handle_task_result
    task.result()
  File "/app/hikcamerabot/services/alarm/camera/tasks/notifications.py", line 32, in run
    await self._run()
  File "/app/hikcamerabot/services/alarm/camera/tasks/notifications.py", line 74, in _run
    await self._send_pic()
  File "/app/hikcamerabot/services/alarm/camera/tasks/notifications.py", line 79, in _send_pic
    photo, ts = await self._cam.take_snapshot(channel=channel, resize=resize)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hikcamerabot/camera.py", line 172, in take_snapshot
    raise HikvisionCamError(err_msg) from err
hikcamerabot.exceptions.HikvisionCamError: [cam_1] Failed to resize snapshot taken from Alabushevo`

**Comment by tropicoo** [comment]
Hello, please try to locally edit the file https://github.com/tropicoo/hikvision-camera-bot/blob/cae39cff671c0315dff6f658e0cf7bbd698123b8/hikcamerabot/utils/image.py

By changing the 6th line (import `ImageFile`) and adding a new 22nd line (`ImageFile.LOAD_TRUNCATED_IMAGES = True`) like in the screenshot. Then rebuild and restart the bot.

![image](https://github.com/tropicoo/hikvision-camera-bot/assets/888784/be22c106-a3c1-4dd2-b291-a40de2bcd5c3)

**Comment by Blogoslov** [comment]
Great, it works fine now. Thanks for the quick solution!
