### ISSUE TITLE
NVR support

### ISSUE THREAD

**Issue by ferdytao** [tropicoo/hikvision-camera-bot#115]
I'm using the option

`"nvr":
    "is_behind": true
     "channel_name": ""`

If i set the channel id eg. "8" is not woking, if i put the name of the camera is not working. Is there a a way to find what the code expect?

**Comment by tropicoo** [comment]
Please post logs

**Comment by ferdytao** [comment]
This is the log, I suppose I should insert `hikvision_camera_bot  | <dynChannelID>8</dynChannelID>` number 8 but it's not working

```
hikvision_camera_bot  | 2023-10-12 21:44:53,090 - [INFO] - [NvrAlarmMonitoringTask:51] - Starting NVR Alarm Monitoring Task
hikvision_camera_bot  | 2023-10-12 21:44:53,110 - [INFO] - [httpx:1729] - HTTP Request: GET http://192.168.1.6/ISAPI/Event/notification/alertStream "HTTP/1.0 200 OK"
hikvision_camera_bot  | 2023-10-12 21:49:08,178 - [ERROR] - [NvrAlarmMonitoringTask:70] - Unknown exception in "NvrAlarmMonitoringTask" for "http://192.168.1.6". Retrying in 0.5 seconds...
hikvision_camera_bot  | Traceback (most recent call last):
hikvision_camera_bot  |   File "/app/hikcamerabot/services/alarm/nvr/tasks/alarm_monitoring_task.py", line 53, in run
hikvision_camera_bot  |     await self._process_chunks()
hikvision_camera_bot  |   File "/app/hikcamerabot/services/alarm/nvr/tasks/alarm_monitoring_task.py", line 91, in _process_chunks
hikvision_camera_bot  |     cam = self._parse_cam(chunk)
hikvision_camera_bot  |           ^^^^^^^^^^^^^^^^^^^^^^
hikvision_camera_bot  |   File "/app/hikcamerabot/services/alarm/nvr/tasks/alarm_monitoring_task.py", line 102, in _parse_cam
hikvision_camera_bot  |     raise RuntimeError(f'Could not find NVR channel name in chunk: "{chunk}"')
hikvision_camera_bot  | RuntimeError: Could not find NVR channel name in chunk: "--boundary
hikvision_camera_bot  | Content-Type: application/xml; charset="UTF-8"
hikvision_camera_bot  | Content-Length: 969
hikvision_camera_bot  |
hikvision_camera_bot  | <EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
hikvision_camera_bot  | <ipAddress>192.168.1.6</ipAddress>
hikvision_camera_bot  | <portNo>80</portNo>
hikvision_camera_bot  | <protocol>HTTP</protocol>
hikvision_camera_bot  | <macAddress>98:df:82:d5:aa:16</macAddress>
hikvision_camera_bot  | <dynChannelID>8</dynChannelID>
hikvision_camera_bot  | <dateTime>2023-10-12T21:49:07</dateTime>
hikvision_camera_bot  | <activePostCount>1</activePostCount>
hikvision_camera_bot  | <eventType>fielddetection</eventType>
hikvision_camera_bot  | <eventState>active</eventState>
hikvision_camera_bot  | <eventDescription>fielddetection alarm</eventDescription>
hikvision_camera_bot  | <DetectionRegionList>
hikvision_camera_bot  | <DetectionRegionEntry>
hikvision_camera_bot  | <regionID></regionID>
hikvision_camera_bot  | <sensitivityLevel>0</sensitivityLevel>
hikvision_camera_bot  | <RegionCoordinatesList>
hikvision_camera_bot  | </RegionCoordinatesList>
hikvision_camera_bot  | </DetectionRegionEntry>
hikvision_camera_bot  | </DetectionRegionList>
hikvision_camera_bot  | <detectionPictureTransType>url</detectionPictureTransType>
hikvision_camera_bot  | <detectionPicturesNumber>1</detectionPicturesNumber>
hikvision_camera_bot  | <bkgUrl>http://192.168.1.6:80/picture/Streaming/tracks/803/?name=ch00008_00000000249005846272000189942&amp;size=189942</bkgUrl>
hikvision_camera_bot  | <URLCertificationType>digest</URLCertificationType>
hikvision_camera_bot  | </EventNotificationAlert>
hikvision_camera_bot  | "
hikvision_camera_bot  | 2023-10-12 21:49:08,682 - [INFO] - [NvrAlarmMonitoringTask:51] - Starting NVR Alarm Monitoring Task
hikvision_camera_bot  | 2023-10-12 21:49:08,704 - [INFO] - [httpx:1729] - HTTP Request: GET http://192.168.1.6/ISAPI/Event/notification/alertStream "HTTP/1.0 200 OK"
hikvision_camera_bot  | 2023-10-12 21:50:52,048 - [ERROR] - [NvrAlarmMonitoringTask:70] - Unknown exception in "NvrAlarmMonitoringTask" for "http://192.168.1.6". Retrying in 0.5 seconds...
hikvision_camera_bot  | Traceback (most recent call last):
hikvision_camera_bot  |   File "/app/hikcamerabot/services/alarm/nvr/tasks/alarm_monitoring_task.py", line 53, in run
hikvision_camera_bot  | <EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
hikvision_camera_bot  | <ipAddress>192.168.1.6</ipAddress>
hikvision_camera_bot  | 2023-10-12 21:50:52,551 - [INFO] - [NvrAlarmMonitoringTask:51] - Starting NVR Alarm Monitoring Task
hikvision_camera_bot  | 2023-10-12 21:50:52,574 - [INFO] - [httpx:1729] - HTTP Request: GET http://192.168.1.6/ISAPI/Event/notification/alertStream "HTTP/1.0 200 OK"
hikvision_camera_bot  | 2023-10-12 21:53:13,638 - [ERROR] - [NvrAlarmMonitoringTask:70] - Unknown exception in "NvrAlarmMonitoringTask" for "http://192.168.1.6". Retrying in 0.5 seconds...
hikvision_camera_bot  | Traceback (most recent call last):
hikvision_camera_bot  |   File "/app/hikcamerabot/services/alarm/nvr/tasks/alarm_monitoring_task.py", line 53, in run
hikvision_camera_bot  |     await self._process_chunks()
hikvision_camera_bot  |     cam = self._parse_cam(chunk)
hikvision_camera_bot  |           ^^^^^^^^^^^^^^^^^^^^^^
hikvision_camera_bot  |   File "/app/hikcamerabot/services/alarm/nvr/tasks/alarm_monitoring_task.py", line 102, in _parse_cam
hikvision_camera_bot  |     raise RuntimeError(f'Could not find NVR channel name in chunk: "{chunk}"')
hikvision_camera_bot  | RuntimeError: Could not find NVR channel name in chunk: "--boundary
hikvision_camera_bot  | Content-Type: application/xml; charset="UTF-8"
hikvision_camera_bot  | Content-Length: 969
hikvision_camera_bot  |
hikvision_camera_bot  | <EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
hikvision_camera_bot  | <ipAddress>192.168.1.6</ipAddress>
hikvision_camera_bot  | <portNo>80</portNo>
hikvision_camera_bot  | <protocol>HTTP</protocol>
hikvision_camera_bot  | <macAddress>98:df:82:d5:aa:16</macAddress>
hikvision_camera_bot  | <dynChannelID>7</dynChannelID>
hikvision_camera_bot  | <dateTime>2023-10-12T21:53:13</dateTime>
hikvision_camera_bot  | <activePostCount>1</activePostCount>
hikvision_camera_bot  | <eventType>fielddetection</eventType>
hikvision_camera_bot  | 2023-10-12 21:53:14,142 - [INFO] - [NvrAlarmMonitoringTask:51] - Starting NVR Alarm Monitoring Task
hikvision_camera_bot  | 2023-10-12 21:53:14,162 - [INFO] - [httpx:1729] - HTTP Request: GET http://192.168.1.6/ISAPI/Event/notification/alertStream "HTTP/1.0 200 OK"
hikvision_camera_bot  | 2023-10-12 21:53:16,731 - [ERROR] - [NvrAlarmMonitoringTask:70] - Unknown exception in "NvrAlarmMonitoringTask" for "http://192.168.1.6". Retrying in 0.5 seconds...
hikvision_camera_bot  | Traceback (most recent call last):
hikvision_camera_bot  | 2023-10-12 21:53:17,234 - [INFO] - [NvrAlarmMonitoringTask:51] - Starting NVR Alarm Monitoring Task
hikvision_camera_bot  | 2023-10-12 21:53:17,253 - [INFO] - [httpx:1729] - HTTP Request: GET http://192.168.1.6/ISAPI/Event/notification/alertStream "HTTP/1.0 200 OK"
hikvision_camera_bot  | 2023-10-12 22:00:10,959 - [ERROR] - [NvrAlarmMonitoringTask:70] - Unknown exception in "NvrAlarmMonitoringTask" for "http://192.168.1.6". Retrying in 0.5 seconds...
hikvision_camera_bot  | Traceback (most recent call last):
hikvision_camera_bot  |     raise RuntimeError(f'Could not find NVR channel name in chunk: "{chunk}"')
hikvision_camera_bot  | RuntimeError: Could not find NVR channel name in chunk: "--boundary
hikvision_camera_bot  | Content-Type: application/xml; charset="UTF-8"
hikvision_camera_bot  | Content-Length: 969
hikvision_camera_bot  |
hikvision_camera_bot  | <EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
hikvision_camera_bot  | <ipAddress>192.168.1.6</ipAddress>
hikvision_camera_bot  | <portNo>80</portNo>
hikvision_camera_bot  | 2023-10-12 22:00:11,466 - [INFO] - [NvrAlarmMonitoringTask:51] - Starting NVR Alarm Monitoring Task
hikvision_camera_bot  | 2023-10-12 22:00:11,493 - [INFO] - [httpx:1729] - HTTP Request: GET http://192.168.1.6/ISAPI/Event/notification/alertStream "HTTP/1.0 200 OK"

```

**Comment by tropicoo** [comment]
I believe there should have been a configurable `channelName` like in the example below.

```xml
2022-11-22T17:48:40.021383713Z <dynChannelID>5</dynChannelID>
2022-11-22T17:48:40.021396005Z <channelID>5</channelID>
2022-11-22T17:48:40.021488009Z <channelName>Front Yard</channelName>
```

Could you please check whether you can set that name in your NVR so the field would appear (if yes, then you won't see that error because the bot searches for the `channelName` and would select `Front Yard` from the example).

**Comment by ferdytao** [comment]
Checked everywhere on my NVR, I changed the camera name from SETTINGS (on top) >> IMAGE (left) >> OSD SETTINGS but it does not show up on logs

**Comment by tropicoo** [comment]
Okay, I will add `dynChannelID` and `channelID` to the NVR config.

**Comment by ferdytao** [comment]
Thank you! Really appreciated!

**Comment by ferdytao** [comment]
I think i fixed it editing chunk.py this way:

```
class CameraNvrChannelNameDetector:
    DETECTION_REGEX = re.compile(
        r'(<channelName>|'
        r'<dynChannelID>|'
        r'<channelID>)(.*)</(channelName|dynChannelID|channelID)>',
        re.MULTILINE,
    )
    DETECTION_KEY_GROUP = 2
```

Just play around with "delay", "recod_time" and "rewind_time" as the video sent is later delayed from when the alarm is triggered.

Thanks for your work btw!

**Comment by ferdytao** [comment]
I fixed changing chunk.py this way:

```
class CameraNvrChannelNameDetector:
    DETECTION_REGEX = re.compile(
        r'(<channelName>|'
        r'<dynChannelID>|'
        r'<channelID>)(.*)</(channelName|dynChannelID|channelID)>',
        re.MULTILINE,
    )
    DETECTION_KEY_GROUP = 2
```

I just need to fine tune something else as the image from NVR is not clean:
![image](https://github.com/tropicoo/hikvision-camera-bot/assets/40245752/f1b7d624-c88c-4790-8b3d-411a647ee519)
