### ISSUE TITLE
Duplicated events and mixed up camera names

### ISSUE THREAD

**Issue by JulyIghor** [tropicoo/hikvision-camera-bot#123]
I have attached the config I use.
There are two cameras.

It is working to send a Video files every 30 minutes, but every time it sends duplicated videos and sometimes wrong name of a camera. Please confirm that my config is correct, if it is, a bug fix needed.

Example, I'm getting two exactly the same videos one by one:
Video from Вхід #vhid
Video from Двір #dvir
And another two videos for the second camera, exactly the same with different labels:
Video from Вхід #vhid
Video from Двір #dvir

````
{
    "telegram":
    {
        "api_id": 0000000,
        "api_hash": "....",
        "lang_code": "en",
        "token": "....:....",
        "chat_users":
        [
            14000000000
        ],
        "alert_users":
        [
            14000000000
        ],
        "startup_message_users":
        [
            14000000000
        ]
    },
    "log_level": "INFO",
    "camera_list":
    {
        "cam_1":
        {
            "hidden": false,
            "description": "Двір",
            "hashtag": "dvir",
            "group": "Default",
            "api":
            {
                "host": "http://....",
                "port": 80,
                "auth":
                {
                    "user": "telegram",
                    "password": "....",
                    "type": "digest_cached"
                },
                "stream_timeout": 10
            },
            "rtsp_port": 554,
            "nvr":
            {
                "is_behind": false,
                "channel_name": ""
            },
            "picture":
            {
                "on_demand":
                {
                    "channel": 101
                },
                "on_alert":
                {
                    "channel": 101
                }
            },
            "video_gif":
            {
                "on_demand":
                {
                    "channel": 101,
                    "record_time": 10,
                    "rewind_time": 10,
                    "tmp_storage": "/tmp",
                    "loglevel": "error",
                    "rtsp_transport_type": "tcp"
                },
                "on_alert":
                {
                    "channel": 101,
                    "record_time": 10,
                    "rewind_time": 10,
                    "rewind": true,
                    "tmp_storage": "/tmp",
                    "loglevel": "error",
                    "rtsp_transport_type": "tcp"
                }
            },
            "alert":
            {
                "delay": 15,
                "motion_detection":
                {
                    "enabled": true,
                    "sendpic": true,
                    "fullpic": false,
                    "send_videogif": true,
                    "send_text": true
                },
                "line_crossing_detection":
                {
                    "enabled": false,
                    "sendpic": true,
                    "fullpic": false,
                    "send_videogif": true,
                    "send_text": true
                },
                "intrusion_detection":
                {
                    "enabled": false,
                    "sendpic": true,
                    "fullpic": false,
                    "send_videogif": true,
                    "send_text": true
                }
            },
            "livestream":
            {
                "youtube":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_youtube"
                },
                "telegram":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_telegram"
                },
                "srs":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_srs"
                },
                "dvr":
                {
                    "enabled": true,
                    "local_storage_path": "/data/dvr",
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_dvr",
                    "upload":
                    {
                        "delete_after_upload": true,
                        "storage":
                        {
                            "telegram":
                            {
                                "enabled": true,
                                "group_id": -1001234567890
                            }
                        }
                    }
                },
                "icecast":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "vp9.kitchen"
                }
            },
            "command_sections_visibility":
            {
                "general": true,
                "infrared": false,
                "motion_detection": true,
                "line_detection": false,
                "intrusion_detection": false,
                "alert_service": false,
                "stream_youtube": false,
                "stream_telegram": true,
                "stream_icecast": false
            }
        },
        "cam_2":
        {
            "hidden": false,
            "description": "Вхід",
            "hashtag": "vhid",
            "group": "Default",
            "api":
            {
                "host": "http://..",
                "port": 80,
                "auth":
                {
                    "user": "telegram",
                    "password": "...",
                    "type": "basic"
                },
                "stream_timeout": 10
            },
            "rtsp_port": 554,
            "nvr":
            {
                "is_behind": false,
                "channel_name": ""
            },
            "picture":
            {
                "on_demand":
                {
                    "channel": 101
                },
                "on_alert":
                {
                    "channel": 101
                }
            },
            "video_gif":
            {
                "on_demand":
                {
                    "channel": 101,
                    "record_time": 10,
                    "rewind_time": 10,
                    "tmp_storage": "/tmp",
                    "loglevel": "error",
                    "rtsp_transport_type": "tcp"
                },
                "on_alert":
                {
                    "channel": 101,
                    "record_time": 10,
                    "rewind_time": 10,
                    "rewind": true,
                    "tmp_storage": "/tmp",
                    "loglevel": "error",
                    "rtsp_transport_type": "tcp"
                }
            },
            "alert":
            {
                "delay": 15,
                "motion_detection":
                {
                    "enabled": true,
                    "sendpic": true,
                    "fullpic": false,
                    "send_videogif": true,
                    "send_text": true
                },
                "line_crossing_detection":
                {
                    "enabled": false,
                    "sendpic": true,
                    "fullpic": false,
                    "send_videogif": true,
                    "send_text": true
                },
                "intrusion_detection":
                {
                    "enabled": false,
                    "sendpic": true,
                    "fullpic": false,
                    "send_videogif": true,
                    "send_text": true
                }
            },
            "livestream":
            {
                "youtube":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_youtube"
                },
                "telegram":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_telegram"
                },
                "srs":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_srs"
                },
                "dvr":
                {
                    "enabled": true,
                    "local_storage_path": "/data/dvr",
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "direct.kitchen_dvr",
                    "upload":
                    {
                        "delete_after_upload": true,
                        "storage":
                        {
                            "telegram":
                            {
                                "enabled": true,
                                "group_id": -1001234567890
                            }
                        }
                    }
                },
                "icecast":
                {
                    "enabled": false,
                    "livestream_template": "tpl_kitchen",
                    "encoding_template": "vp9.kitchen"
                }
            },
            "command_sections_visibility":
            {
                "general": true,
                "infrared": false,
                "motion_detection": true,
                "line_detection": false,
                "intrusion_detection": false,
                "alert_service": false,
                "stream_youtube": false,
                "stream_telegram": true,
                "stream_icecast": false
            }
        }
    }
}
````

**Comment by tropicoo** [comment]
Could you please send logs

**Comment by tropicoo** [comment]
Are these videos from motion detection or DVR?

**Comment by tropicoo** [comment]
Please pull the latest changes. Should be fixed now.

**Comment by tropicoo** [comment]
> for the same events.

Are you talking about the Motion Detection?

**Comment by tropicoo** [comment]
I will try to reproduce.

**Comment by tropicoo** [comment]
Could you send the debug logs again when this happens?

**Comment by tropicoo** [comment]
Also, pull the latest changes.

**Comment by tropicoo** [comment]
1. I don't believe my last change is related to high CPU usage, you can go inside the container `docker exec -it hikvision_camera_bot bash`, run `htop`, press `F5` on the keyboard and see what's consuming the CPU - ffmpeg processes or python. You can post the screenshot.
2. I've checked your log and didn't see that some file was uploaded twice:
```python
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_04-42-48.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_04-47-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_04-52-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_04-57-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-02-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-07-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-12-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-17-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-22-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-27-51.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-32-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-37-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-42-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-47-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-52-49.mp4',
'Uploading DVR video /data/dvr/cam_2_101_300_2023-12-16_05-57-49.mp4',
```
So that's strange. Do these videos that were uploaded twice have the same filename? If your right click on it and press "Save as", you'll see the original filename.

3. I've handled this error and you should see `Failed to gather video stream metadata:` error message with full `ffprobe` context dictionary. I would need to see it and investigate.
```python
Traceback (most recent call last):
  File "/app/hikcamerabot/services/stream/dvr/tasks/file_monitoring.py", line 33, in _monitor_dvr_files
    await self._engine.upload_files(await self._get_unlocked_files())
  File "/app/hikcamerabot/services/stream/dvr/upload/engine.py", line 48, in upload_files
    for file_ in await self._wrap_as_dvr_files(files):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/hikcamerabot/services/stream/dvr/upload/engine.py", line 58, in _wrap_as_dvr_files
    await asyncio.gather(*[f.make_context() for f in files])
  File "/app/hikcamerabot/services/stream/dvr/file_wrapper.py", line 65, in make_context
    await asyncio.gather(self._get_probe_ctx(), self._make_thumbnail_frame())
  File "/app/hikcamerabot/services/stream/dvr/file_wrapper.py", line 56, in _get_probe_ctx
    self._duration = int(float(self._probe_ctx['format']['duration']))
                               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'duration'
```

Pull the latest changes again.

**Comment by tropicoo** [comment]
> Here it is
[duplicated_log.txt](https://github.com/tropicoo/hikvision-camera-bot/files/13709059/duplicated_log.txt)

And in this case what's the filename of the duplicated video?

**Comment by tropicoo** [comment]
Unfortunately, these files aren't in the log file.

**Comment by tropicoo** [comment]
I believe I've found the issue. Please pull the latest changes.
