### ISSUE TITLE
Can`t lanch bot.py

### ISSUE THREAD

**Issue by khurshidbekrumak** [tropicoo/hikvision-camera-bot#15]
shoow this error

`Traceback (most recent call last):
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/bot.py", line 113, in <module>
    BOT = CameraBotLauncher()
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/bot.py", line 47, in __init__
    cam_pool, cmds = self._create_cameras()
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/bot.py", line 88, in _create_cameras
    cam_pool.add(cam_id, cam_cmds, HomeCam(conf=cam_conf))
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/camerabot/homecam.py", line 63, in __init__
    hik_host=conf.api.host)
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/camerabot/livestream.py", line 202, in __init__
    super().__init__(STREAMS.YOUTUBE, conf, hik_user, hik_password, hik_host)
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/camerabot/livestream.py", line 53, in __init__
    self._generate_cmd()
  File "/home/khurshidbek/PycharmProjects/hikvision-camera-bot/camerabot/livestream.py", line 150, in _generate_cmd
    channel=self._stream_conf.channel,
AttributeError: 'NoneType' object has no attribute 'channel'

Process finished with exit code 1`

**Comment by tropicoo** [comment]
Hi,
Please make `git pull`
And verify that you've copied:
1. `config-template.json -> config.json`
2. `encoding_templates-template.json -> encoding_templates.json`
3. `livestream_templates-template.json -> livestream_templates.json`

And that you have written valid config values into `config.json`:
1. Token ID
2. User ID
3. Camera address
4. Camera user
5. Camera password
