### ISSUE TITLE
Ошибки при запуске? 

### ISSUE THREAD

**Issue by vladios13** [tropicoo/hikvision-camera-bot#18]
Запуская бота получаю такие ошибки в консоли:  
```
Traceback (most recent call last):
  File "C:/hickvision_camera/bot.py", line 125, in <module>
    bot_engine.run()
  File "C:/hickvision_camera/bot.py", line 63, in run
    self._updater.bot.start_processes()
File "C:\hickvision_camera\hikcamerabot\camerabot.py", line 39, in start_processes
    self.proc_manager.start_processes()
  File "C:\hickvision_camera\hikcamerabot\managers\process.py", line 28, in start_processes
    proc.start()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread._local' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
Запускаю через PYcharm на Windows, установлен Python 3.8, что бы проверить работу бота. 
Спасибо за любые комментарии.

**Comment by tropicoo** [comment]
Это как-то связано с Pycharm, рекомендую запускать в терминале.

**Comment by vladios13** [comment]
> Это как-то связано с Pycharm, рекомендую запускать в терминале.

Спасибо, буду пробовать запуск из под терминала.
