### ISSUE TITLE
Не срабатывает Motion Detection

### ISSUE THREAD

**Issue by vladios13** [tropicoo/hikvision-camera-bot#19]
При запуске бота, проскакивает такое:
```Exception in thread ServiceAlarmPusherThread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/Desktop/tgbots/hikvision-camera-bot/hikcamerabot/services/threads.py", line 56, in run
    self._process_chunks()
  File "/root/Desktop/tgbots/hikvision-camera-bot/hikcamerabot/services/threads.py", line 73, in _process_chunks
    detection_key = self._detect_chunk(chunk)
  File "/root/Desktop/tgbots/hikvision-camera-bot/hikcamerabot/services/threads.py", line 86, in _detect_chunk
    match = re.match(DETECTION_REGEX, chunk.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 13: invalid start byte
```
Все настроено по конфигу, по командам пикчи присылает. но motion detection не срабатывает, ничего ни в логах ни боте ничего нет. RTSP поток прописан верно. 102 канал доступен.
Логи говорят что все ок: 
```
2020-01-19 15:54:51,516 - hikcamerabot.callbacks.callbacks:216 - INFO - Enabling camera's alert mode requested
2020-01-19 15:54:51,739 - ResultAlarmConfHandler:119 - INFO - Alarm alert mode already started
```
[Скриншот](https://i.13.yt/2020/01/19/1579439023-5859.png)

Как исправить?  Спасибо за работу.

**Comment by tropicoo** [comment]
Здравствуйте,
Откройте текстовый файл `/root/Desktop/tgbots/hikvision-camera-bot/hikcamerabot/services/threads.py` на 85-й строке, там будет
```python
    def _detect_chunk(self, chunk):
        match = re.match(DETECTION_REGEX, chunk.decode())
```
Добавьте следующие 2 записи
```python
    self._log.info('Got chunk: %s', chunk)
    self._log.info('Chunk type: %s', type(chunk))
    def _detect_chunk(self, chunk):
        match = re.match(DETECTION_REGEX, chunk.decode())
```
Сохраните, спровоцируйте ошибку еще раз и покажите что было написано в логах.

**Comment by vladios13** [comment]
> Сохраните, перезапустите бота, спровоцируйте ошибку еще раз и покажите что было написано в логах.

Прошу прощения что долго держу открым issue, в данный момент жду такую же камеру для продолжения тестирования. Совсем скоро дам полный отчёт в логах.
Спасибо.

**Comment by vladios13** [comment]
> еще раз и покажите что было написано в логах.
Сделал, ниже получил такое:

```
2020-03-07 15:30:10,449 - hikcamerabot.callbacks.callbacks:216 - INFO - Enabling camera's alert mode requested
2020-03-07 15:30:10,566 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'--boundary'
2020-03-07 15:30:10,566 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,567 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'Content-Type: application/xml; charset="UTF-8"'
2020-03-07 15:30:10,567 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,567 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'Content-Length: 527'
2020-03-07 15:30:10,567 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,567 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver10/XMLSchema">'
2020-03-07 15:30:10,567 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,568 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<ipAddress>192.168.1.38</ipAddress>'
2020-03-07 15:30:10,568 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,568 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<portNo>80</portNo>'
2020-03-07 15:30:10,568 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,568 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<protocol>HTTP</protocol>'
2020-03-07 15:30:10,568 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<macAddress>bc:ba:c2:52:09:2d</macAddress>'
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<channelID>1</channelID>'
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<dateTime>2020-03-07T15:30:00+03:00</dateTime>'
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<activePostCount>0</activePostCount>'
2020-03-07 15:30:10,569 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>

```

**Comment by vladios13** [comment]
> > еще раз и покажите что было написано в логах.

@tropicoo очень надеюсь на Вашу помощь.

**Comment by tropicoo** [comment]
Здравствуйте, протестируйте пожалуйста, проблема должна быть исправлена.
Насчет второй откройте отдельный issue, спасибо.

**Comment by vladios13** [comment]
> Здравствуйте, протестируйте пожалуйста, проблема должна быть исправлена.
> Насчет второй откройте отдельный issue, спасибо.

Спасибо что откликнулись. Я заново скопировал исходники и запустил.
Теперь при включении _Alarm Mode_ в консоли нет ошибок, но по прежнему ничего **не приходит** в Telegram при движении.

![ssh](https://user-images.githubusercontent.com/10531221/78598246-a8574180-7857-11ea-98f2-93ffb8199b02.jpg)

**Comment by tropicoo** [comment]
Включите `DEBUG` режим в `config.json`, там должно быть больше детализированных записей:
  `"log_level": "DEBUG",`

**Comment by vladios13** [comment]
> Включите `DEBUG` режим в `config.json`, там должно быть больше детализированных записей:
> `"log_level": "DEBUG",`

Уважаемый @tropicoo, если есть возможность, напишите мне пожалуйста в Telegram "@vladios13".
Спасибо.

**Comment by vladios13** [comment]
> Включите `DEBUG` режим в `config.json`, там должно быть больше детализированных записей:
> `"log_level": "DEBUG",`

Выставил DEBUG режим для Alarm. 
Видно что срабатывает запись mp4 файла ffmpeg-ом. Но получаю все так же ошибки. 

![IMG_20200407_074525](https://user-images.githubusercontent.com/10531221/78631089-04e04e00-78a4-11ea-84ba-bde861b7ba99.jpg)

"DEBUG" стоит включить для всей камеры? Для полной детализации?

**Comment by vladios13** [comment]
> > Включите `DEBUG` режим в `config.json`, там должно быть больше детализированных записей:
> > `"log_level": "DEBUG",`
> 
> Выставил DEBUG режим для Alarm.
> Видно что срабатывает запись mp4 файла ffmpeg-ом. Но получаю все так же ошибки.
> 
> ![IMG_20200407_074525](https://user-images.githubusercontent.com/10531221/78631089-04e04e00-78a4-11ea-84ba-bde861b7ba99.jpg)
> 
Уважаемый @tropicoo, я кажется понял в чем причина.
FFMPEG обращается по **rtsp каналу на 82** порту (_в моем случае_) где открыто HTTP соединение. Но, но у меня rtsp порт открыт на **557**. 
Значит сформированная ссылка: `rtsp://admin:admin@mydomain.com:82/Streaming/channels/102` не верна.
Как я понимаю должно быть что то вроде этого: 
`rtsp://admin:admin@mydomain.com:557/Streaming/channels/102`
Как изменить порт для rtsp, не трогая при этом http порт в `config.json`

**Comment by tropicoo** [comment]
Fixed
