### ISSUE TITLE
Ошибка авторизации? 

### ISSUE THREAD

**Issue by vladios13** [tropicoo/hikvision-camera-bot#20]
При запуске бота получаю в логи: 
`
2020-01-19 19:22:24,853 - HikvisionAPI:141 - ERROR - Failed to query API: Unhandled response code: 405
`
```
Access Error: 405 -- Method Not Allowed
Requested method GET not supported for URL: /Streaming/channels/101/picture
```

Камера: DT185-I
В ней нет пункта для выполнения CGI скриптов, но я активировал "Включить WebSockets". 

При запросе на получение картинки получаю: 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/Desktop/tgbots/camera/hikvision-camera-bot/hikcamerabot/handlers/__init__.py", line 81, in run
    self._dispatcher.handle(data)
  File "/root/Desktop/tgbots/camera/hikvision-camera-bot/hikcamerabot/decorators.py", line 54, in wrapper
    cam_id, update = handler._bot._updates.pop(data['event_id'])
AttributeError: 'ResultDispatcher' object has no attribute '_bot'

```

**Comment by vladios13** [comment]
Исправил: 
нужно было изменить строку в файле в файл: **hikvision-camera-bot/hikcamerabot/core/api.py**
[link](https://github.com/tropicoo/hikvision-camera-bot/blob/master/hikcamerabot/core/api.py#L23)

`PICTURE =Streaming/channels/101/picture?snapShotImageType=JPEG"`
добавив префикс `f"{_ISAPI_PREFIX}` что бы получилось так: 
`PICTURE = f"{_ISAPI_PREFIX}/Streaming/channels/101/picture?snapShotImageType=JPEG"`
