### ISSUE TITLE
chunk error log

### ISSUE THREAD

**Issue by vladios13** [tropicoo/hikvision-camera-bot#23]
> еще раз и покажите что было написано в логах.

UPD: также при повторном запуске бота и созданием движения иногда получаю и такое: 
```
2020-03-07 17:27:25,093 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'--boundary'
2020-03-07 17:27:25,093 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,094 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'Content-Type: application/xml; charset="UTF-8"'
2020-03-07 17:27:25,094 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,094 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'Content-Length: 563'
2020-03-07 17:27:25,094 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,094 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver10/XMLSchema">'
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<ipAddress>192.168.1.38</ipAddress>'
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<portNo>80</portNo>'
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<protocol>HTTP</protocol>'
2020-03-07 17:27:25,095 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,096 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<macAddress>bc:ba:c2:52:09:2d</macAddress>'
2020-03-07 17:27:25,096 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,096 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<channelID>1</channelID>'
2020-03-07 17:27:25,096 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,096 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<dateTime>2020-03-07T17:27:15+03:00</dateTime>'
2020-03-07 17:27:25,096 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,097 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<activePostCount>1</activePostCount>'
2020-03-07 17:27:25,097 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
2020-03-07 17:27:25,097 - ServiceAlarmPusherThread:86 - INFO - Got chunk: b'<eventType>VMD</eventType>'
2020-03-07 17:27:25,097 - ServiceAlarmPusherThread:87 - INFO - Chunk type: <class 'bytes'>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/Desktop/tgbots/camera-kotel/hikcamerabot/handlers/__init__.py", line 81, in run
    self._dispatcher.handle(data)
  File "/root/Desktop/tgbots/camera-kotel/hikcamerabot/decorators.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/root/Desktop/tgbots/camera-kotel/hikcamerabot/handlers/__init__.py", line 64, in handle
    self._dispatch_map[data['event']](data)
  File "/root/Desktop/tgbots/camera-kotel/hikcamerabot/handlers/result_event_handlers.py", line 18, in __call__
    self._handle(data)
  File "/root/Desktop/tgbots/camera-kotel/hikcamerabot/handlers/result_event_handlers.py", line 94, in _handle
    timeout=SEND_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 407, in send_photo
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 322, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 238, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: File must be non-empty

```

_Originally posted by @vladios13 in https://github.com/tropicoo/hikvision-camera-bot/issues/19#issuecomment-596083424_

**Comment by tropicoo** [comment]
Fixed in branch 28
